/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;
import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author Lizy Bustillo
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    
    public double[] numeros = new double[2];
    public boolean decimal = true;
    public boolean division = false;
    public boolean multi = false;
    public boolean resta = false;
    public boolean suma = false;
    public boolean porc = false;
    public boolean signo = false;
    
    public Pantalla() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNum = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnSigno = new javax.swing.JButton();
        btnPorc = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(76, 76, 83));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtNum.setEditable(false);
        txtNum.setBackground(new java.awt.Color(76, 76, 83));
        txtNum.setFont(new java.awt.Font("Arial", 0, 52)); // NOI18N
        txtNum.setForeground(new java.awt.Color(255, 255, 255));
        txtNum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNum.setAlignmentX(0.0F);
        txtNum.setAutoscrolls(false);
        txtNum.setBorder(null);
        txtNum.setCaretColor(new java.awt.Color(76, 76, 83));
        txtNum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNum.setMargin(new java.awt.Insets(5, 5, 5, 5));
        txtNum.setMaximumSize(new java.awt.Dimension(0, 0));
        txtNum.setMinimumSize(new java.awt.Dimension(0, 0));

        btnBorrar.setBackground(new java.awt.Color(92, 94, 104));
        btnBorrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("AC");
        btnBorrar.setBorderPainted(false);
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBorrar.setFocusPainted(false);
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrarMouseExited(evt);
            }
        });
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnSigno.setBackground(new java.awt.Color(92, 94, 104));
        btnSigno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSigno.setForeground(new java.awt.Color(255, 255, 255));
        btnSigno.setText("+/-");
        btnSigno.setBorderPainted(false);
        btnSigno.setFocusPainted(false);
        btnSigno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignoMouseExited(evt);
            }
        });
        btnSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoActionPerformed(evt);
            }
        });

        btnPorc.setBackground(new java.awt.Color(92, 94, 104));
        btnPorc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPorc.setForeground(new java.awt.Color(255, 255, 255));
        btnPorc.setText("%");
        btnPorc.setBorderPainted(false);
        btnPorc.setFocusPainted(false);
        btnPorc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPorcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPorcMouseExited(evt);
            }
        });
        btnPorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcActionPerformed(evt);
            }
        });

        btnDivision.setBackground(new java.awt.Color(255, 159, 6));
        btnDivision.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(255, 255, 255));
        btnDivision.setText("÷");
        btnDivision.setBorderPainted(false);
        btnDivision.setFocusPainted(false);
        btnDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDivisionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDivisionMouseExited(evt);
            }
        });
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnSiete.setBackground(new java.awt.Color(124, 125, 128));
        btnSiete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSiete.setForeground(new java.awt.Color(255, 255, 255));
        btnSiete.setText("7");
        btnSiete.setBorderPainted(false);
        btnSiete.setFocusPainted(false);
        btnSiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSieteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSieteMouseExited(evt);
            }
        });
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });

        btnOcho.setBackground(new java.awt.Color(124, 125, 128));
        btnOcho.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnOcho.setForeground(new java.awt.Color(255, 255, 255));
        btnOcho.setText("8");
        btnOcho.setBorderPainted(false);
        btnOcho.setFocusPainted(false);
        btnOcho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOchoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOchoMouseExited(evt);
            }
        });
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });

        btnNueve.setBackground(new java.awt.Color(124, 125, 128));
        btnNueve.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNueve.setForeground(new java.awt.Color(255, 255, 255));
        btnNueve.setText("9");
        btnNueve.setBorderPainted(false);
        btnNueve.setFocusPainted(false);
        btnNueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNueveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNueveMouseExited(evt);
            }
        });
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });

        btnMulti.setBackground(new java.awt.Color(255, 159, 6));
        btnMulti.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(255, 255, 255));
        btnMulti.setText("x");
        btnMulti.setBorderPainted(false);
        btnMulti.setFocusPainted(false);
        btnMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMultiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMultiMouseExited(evt);
            }
        });
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnCuatro.setBackground(new java.awt.Color(124, 125, 128));
        btnCuatro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCuatro.setForeground(new java.awt.Color(255, 255, 255));
        btnCuatro.setText("4");
        btnCuatro.setBorderPainted(false);
        btnCuatro.setFocusPainted(false);
        btnCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCuatroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCuatroMouseExited(evt);
            }
        });
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });

        btnCinco.setBackground(new java.awt.Color(124, 125, 128));
        btnCinco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCinco.setForeground(new java.awt.Color(255, 255, 255));
        btnCinco.setText("5");
        btnCinco.setBorderPainted(false);
        btnCinco.setFocusPainted(false);
        btnCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCincoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCincoMouseExited(evt);
            }
        });
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnSeis.setBackground(new java.awt.Color(124, 125, 128));
        btnSeis.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSeis.setForeground(new java.awt.Color(255, 255, 255));
        btnSeis.setText("6");
        btnSeis.setBorderPainted(false);
        btnSeis.setFocusPainted(false);
        btnSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSeisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeisMouseExited(evt);
            }
        });
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });

        btnResta.setBackground(new java.awt.Color(255, 159, 6));
        btnResta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnResta.setForeground(new java.awt.Color(255, 255, 255));
        btnResta.setText("-");
        btnResta.setBorderPainted(false);
        btnResta.setFocusPainted(false);
        btnResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRestaMouseExited(evt);
            }
        });
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnUno.setBackground(new java.awt.Color(124, 125, 128));
        btnUno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnUno.setForeground(new java.awt.Color(255, 255, 255));
        btnUno.setText("1");
        btnUno.setBorderPainted(false);
        btnUno.setFocusPainted(false);
        btnUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUnoMouseExited(evt);
            }
        });
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        btnDos.setBackground(new java.awt.Color(124, 125, 128));
        btnDos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDos.setForeground(new java.awt.Color(255, 255, 255));
        btnDos.setText("2");
        btnDos.setBorderPainted(false);
        btnDos.setFocusPainted(false);
        btnDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDosMouseExited(evt);
            }
        });
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });

        btnTres.setBackground(new java.awt.Color(124, 125, 128));
        btnTres.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnTres.setForeground(new java.awt.Color(255, 255, 255));
        btnTres.setText("3");
        btnTres.setBorderPainted(false);
        btnTres.setFocusPainted(false);
        btnTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTresMouseExited(evt);
            }
        });
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnSuma.setBackground(new java.awt.Color(255, 159, 6));
        btnSuma.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(255, 255, 255));
        btnSuma.setText("+");
        btnSuma.setBorderPainted(false);
        btnSuma.setFocusPainted(false);
        btnSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSumaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSumaMouseExited(evt);
            }
        });
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnCero.setBackground(new java.awt.Color(124, 125, 128));
        btnCero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCero.setForeground(new java.awt.Color(255, 255, 255));
        btnCero.setText("0");
        btnCero.setBorderPainted(false);
        btnCero.setFocusPainted(false);
        btnCero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCeroMouseExited(evt);
            }
        });
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });

        btnDecimal.setBackground(new java.awt.Color(124, 125, 128));
        btnDecimal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDecimal.setForeground(new java.awt.Color(255, 255, 255));
        btnDecimal.setText(".");
        btnDecimal.setBorderPainted(false);
        btnDecimal.setFocusPainted(false);
        btnDecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDecimalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDecimalMouseExited(evt);
            }
        });
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(255, 159, 6));
        btnIgual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");
        btnIgual.setBorderPainted(false);
        btnIgual.setFocusPainted(false);
        btnIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIgualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIgualMouseExited(evt);
            }
        });
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNum, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.getContentPane().setBackground(this.getBackground());
    }//GEN-LAST:event_formWindowOpened

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "8");
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "9");
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "4");
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "1");
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "3");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        // TODO add your handling code here:
        txtNum.setText(txtNum.getText() + "0");
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        // TODO add your handling code here:
         if (decimal == true) {
            txtNum.setText(txtNum.getText() + ".");
            decimal = false;
        }
    }//GEN-LAST:event_btnDecimalActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        txtNum.setText("");
        
        decimal = true;
        division = false;
        multi = false;
        suma = false;
        resta = false;
        porc = false;
        numeros[0] = 0;
        numeros[1] = 0;
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoActionPerformed
        // TODO add your handling code here:
        try {
            double cambio;
            String entero;
            cambio = Double.parseDouble(txtNum.getText());
            cambio = cambio * -1;
            if (cambio % 1 == 0) { //123.1 % 1 = 0,1 de resto  % hace diviciones exactas para sacar el resto
                entero = Double.toString(cambio);  //1234,0
                txtNum.setText(entero.substring(0, entero.length() - 2)); //1234.0 - 2 = 1234
            } else {
                txtNum.setText(Double.toString(cambio));
            }
        } catch (Exception e) {

        } 
    }//GEN-LAST:event_btnSignoActionPerformed

    private void btnPorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcActionPerformed
        // TODO add your handling code here:
        try {
            numeros[0] = Double.parseDouble(txtNum.getText());
            txtNum.setText("");
            porc = true;
            decimal = true;
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnPorcActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        try {
            numeros[0] = Double.parseDouble(txtNum.getText());
            txtNum.setText("");
            decimal = true;
            division = true;
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        // TODO add your handling code here:
         try {
            numeros[0] = Double.parseDouble(txtNum.getText());
            txtNum.setText("");
            decimal = true;
            multi = true;
        } catch (Exception e) {

        } 
        
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
         try {
            numeros[0] = Double.parseDouble(txtNum.getText());
            txtNum.setText("");
            decimal = true;
            resta = true;
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
          try {
            numeros[0] = Double.parseDouble(txtNum.getText());
            txtNum.setText("");
            suma = true;
            decimal = true;
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
        double resultado = 0;
        DecimalFormat df = new DecimalFormat("#.######");

    try {
    numeros[1] = Double.parseDouble(txtNum.getText());

    if (division == true) {
        if (numeros[1] == 0.0) {
            txtNum.setText("Error");
        } else {
            resultado = numeros[0] / numeros[1];
            txtNum.setText(df.format(resultado));
        }
        } else if (multi == true) {
        resultado = numeros[0] * numeros[1];
        txtNum.setText(df.format(resultado));
        } else if (resta == true) {
        resultado = numeros[0] - numeros[1];
        txtNum.setText(df.format(resultado));
        } else if (suma == true) {
        resultado = numeros[0] + numeros[1];
        txtNum.setText(df.format(resultado));
        } else if (porc == true) {
        resultado = numeros[1] * (numeros[0] / 100.0);
        txtNum.setText(df.format(resultado));
    }
    } catch (Exception e) {
    
 }

        decimal = true;
        division = false;
        multi = false;
        suma = false;
        resta = false;
        porc = false;
        numeros[0] = 0;
        numeros[1] = 0;

    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseEntered
        // TODO add your handling code here:
        btnBorrar.setBackground(new Color(124, 125, 128));  
    }//GEN-LAST:event_btnBorrarMouseEntered

    private void btnBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseExited
        // TODO add your handling code here:
        btnBorrar.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnBorrarMouseExited

    private void btnSignoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignoMouseEntered
        // TODO add your handling code here:
        btnSigno.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnSignoMouseEntered

    private void btnSignoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignoMouseExited
        // TODO add your handling code here:
        btnSigno.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnSignoMouseExited

    private void btnPorcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPorcMouseEntered
        // TODO add your handling code here:
        btnPorc.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnPorcMouseEntered

    private void btnPorcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPorcMouseExited
        // TODO add your handling code here:
        btnPorc.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnPorcMouseExited

    private void btnSieteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSieteMouseEntered
        // TODO add your handling code here:
        btnSiete.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnSieteMouseEntered

    private void btnSieteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSieteMouseExited
        // TODO add your handling code here:
        btnSiete.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnSieteMouseExited

    private void btnOchoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOchoMouseEntered
        // TODO add your handling code here:
        btnOcho.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnOchoMouseEntered

    private void btnOchoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOchoMouseExited
        // TODO add your handling code here:
        btnOcho.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnOchoMouseExited

    private void btnNueveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNueveMouseEntered
        // TODO add your handling code here:
        btnNueve.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnNueveMouseEntered

    private void btnNueveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNueveMouseExited
        // TODO add your handling code here:
        btnNueve.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnNueveMouseExited

    private void btnCuatroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuatroMouseEntered
        // TODO add your handling code here:
        btnCuatro.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnCuatroMouseEntered

    private void btnCuatroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuatroMouseExited
        // TODO add your handling code here:
        btnCuatro.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnCuatroMouseExited

    private void btnCincoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCincoMouseEntered
        // TODO add your handling code here:
        btnCinco.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnCincoMouseEntered

    private void btnCincoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCincoMouseExited
        // TODO add your handling code here:
        btnCinco.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnCincoMouseExited

    private void btnSeisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeisMouseEntered
        // TODO add your handling code here:
        btnSeis.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnSeisMouseEntered

    private void btnSeisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeisMouseExited
        // TODO add your handling code here:
        btnSeis.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnSeisMouseExited

    private void btnUnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnoMouseEntered
        // TODO add your handling code here:
        btnUno.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnUnoMouseEntered

    private void btnUnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnoMouseExited
        // TODO add your handling code here:
        btnUno.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnUnoMouseExited

    private void btnDosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosMouseEntered
        // TODO add your handling code here:
        btnDos.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnDosMouseEntered

    private void btnDosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosMouseExited
        // TODO add your handling code here:
        btnDos.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnDosMouseExited

    private void btnTresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTresMouseEntered
        // TODO add your handling code here:
        btnTres.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnTresMouseEntered

    private void btnTresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTresMouseExited
        // TODO add your handling code here:
        btnTres.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnTresMouseExited

    private void btnCeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCeroMouseEntered
        // TODO add your handling code here:
        btnCero.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnCeroMouseEntered

    private void btnCeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCeroMouseExited
        // TODO add your handling code here:
        btnCero.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnCeroMouseExited

    private void btnDecimalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecimalMouseEntered
        // TODO add your handling code here:
        btnDecimal.setBackground(new Color(92, 94, 104));
    }//GEN-LAST:event_btnDecimalMouseEntered

    private void btnDecimalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecimalMouseExited
        // TODO add your handling code here:
        btnDecimal.setBackground(new Color(124, 125, 128));
    }//GEN-LAST:event_btnDecimalMouseExited

    private void btnDivisionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisionMouseEntered
        // TODO add your handling code here:
        btnDivision.setBackground(new Color(255, 118, 0));
    }//GEN-LAST:event_btnDivisionMouseEntered

    private void btnDivisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisionMouseExited
        // TODO add your handling code here:
        btnDivision.setBackground(new Color(239, 159, 6));
    }//GEN-LAST:event_btnDivisionMouseExited

    private void btnMultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMouseEntered
        // TODO add your handling code here:
        btnMulti.setBackground(new Color(255, 118, 0));
    }//GEN-LAST:event_btnMultiMouseEntered

    private void btnMultiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMouseExited
        // TODO add your handling code here:
        btnMulti.setBackground(new Color(255, 159, 6));
    }//GEN-LAST:event_btnMultiMouseExited

    private void btnRestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseEntered
        // TODO add your handling code here:
        btnResta.setBackground(new Color(255, 118, 0));
    }//GEN-LAST:event_btnRestaMouseEntered

    private void btnRestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseExited
        // TODO add your handling code here:
        btnResta.setBackground(new Color(255, 159, 6));
    }//GEN-LAST:event_btnRestaMouseExited

    private void btnSumaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumaMouseEntered
        // TODO add your handling code here:
        btnSuma.setBackground(new Color(255, 118, 0));
    }//GEN-LAST:event_btnSumaMouseEntered

    private void btnSumaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumaMouseExited
        // TODO add your handling code here:
        btnSuma.setBackground(new Color(255, 159, 6));
    }//GEN-LAST:event_btnSumaMouseExited

    private void btnIgualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualMouseEntered
        // TODO add your handling code here:
        btnIgual.setBackground(new Color(255, 118, 0));
    }//GEN-LAST:event_btnIgualMouseEntered

    private void btnIgualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualMouseExited
        // TODO add your handling code here:
        btnIgual.setBackground(new Color(255, 159, 6));
    }//GEN-LAST:event_btnIgualMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPorc;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnSigno;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
